export const homeEstablished = {
  en: "Est. 1973",
  si: "ස්ථාපිත 1973",
  ta: "நிறுவப்பட்டது 1973",
} as const;

export const homeCopy = {
  en: { imageAlt: "Herbal medicine", pure: "100% Pure", noAdditives: "No additives or preservatives", trusted: "Trusted Since 1973", stats: ["Years of Heritage", "Herbal Ingredients", "Provinces Served", "Natural & Pure"], collectionAlt: "Herbal products", trust: "A Century of Trust", heritage: "Our Heritage", legacy: "A Legacy of Ayurvedic Excellence", heritageOne: "Rajapura Herbal Drugs Co. (Pvt) Ltd is one of Sri Lanka's leading manufacturers and distributors of high-quality herbal medical products, legally registered under the laws of Sri Lanka.", heritageTwo: "Today, we blend ancient wisdom with modern quality standards, bringing nature's healing gifts to households across Sri Lanka—always pure, always authentic.", story: "Learn Our Story", why: "Why Choose Us", difference: "The Rajapura Difference", values: [{ title: "Sustainably Sourced", desc: "Every herb is ethically harvested from certified organic farms and pristine Sri Lankan wilderness." }, { title: "Ayurvedic Certified", desc: "All formulations are approved by Sri Lanka's Department of Ayurveda and traditional physicians." }, { title: "Holistic Wellness", desc: "Our products nurture body, mind and spirit following the tridosha principles of Ayurveda." }, { title: "Zero Chemicals", desc: "No artificial preservatives, colours, or additives—just pure nature in every product." }], collection: "Our Collection", featured: "Featured Products", viewAll: "View All", none: "No products available at the moment.", checkBack: "Please check back soon.", findStore: "Find Store", findProducts: "Find Rajapura Products Near You", available: "Available at pharmacies, Ayurvedic stores, and health centres across all 9 provinces of Sri Lanka.", locator: "Use Store Locator", badges: { Bestseller: "Bestseller", Premium: "Premium", New: "New", Organic: "Organic" } },
  si: { imageAlt: "ඖෂධීය ශාක", pure: "100% පිරිසිදු", noAdditives: "ආකලන හෝ කල් තබාගන්නා ද්‍රව්‍ය නොමැත", trusted: "1973 සිට විශ්වාසය", stats: ["උරුමයේ වසර", "ඖෂධීය අමුද්‍රව්‍ය", "සේවය කරන පළාත්", "ස්වභාවික සහ පිරිසිදු"], collectionAlt: "ඖෂධීය නිෂ්පාදන", trust: "විශ්වාසයේ සියවසක්", heritage: "අපගේ උරුමය", legacy: "ආයුර්වේද විශිෂ්ටත්වයේ උරුමයක්", heritageOne: "රාජපුර හර්බල් ඩ්‍රග්ස් සමාගම ශ්‍රී ලංකාවේ උසස් තත්ත්වයේ ඖෂධීය නිෂ්පාදන ප්‍රමුඛ නිෂ්පාදකයෙකු සහ බෙදාහරින්නෙකු වන අතර ශ්‍රී ලංකා නීතිය යටතේ ලියාපදිංචි වී ඇත.", heritageTwo: "අද අපි පුරාණ ප්‍රඥාව නවීන තත්ත්ව ප්‍රමිතීන් සමඟ එක් කර සොබාදහමේ සුවදායක ත්‍යාග ශ්‍රී ලංකාව පුරා නිවෙස් වෙත ගෙන එන්නෙමු—සැමවිටම පිරිසිදු සහ අව්‍යාජ.", story: "අපගේ කතාව දැනගන්න", why: "අප තෝරාගන්නේ ඇයි", difference: "රාජපුර වෙනස", values: [{ title: "තිරසාර මූලාශ්‍ර", desc: "සෑම ඖෂධ පැළෑටියක්ම සහතික ලත් කාබනික ගොවිපළවලින් සහ පිරිසිදු ශ්‍රී ලාංකේය වනයෙන් සදාචාරාත්මකව ලබා ගනී." }, { title: "ආයුර්වේද සහතිකය", desc: "සියලු සූත්‍ර ශ්‍රී ලංකා ආයුර්වේද දෙපාර්තමේන්තුව සහ පාරම්පරික වෛද්‍යවරුන් විසින් අනුමත කර ඇත." }, { title: "සම්පූර්ණ සුවතාව", desc: "අපගේ නිෂ්පාදන ත්‍රිදෝෂ මූලධර්ම අනුව ශරීරය, මනස සහ ආත්මය පෝෂණය කරයි." }, { title: "රසායනික ද්‍රව්‍ය නොමැත", desc: "කෘත්‍රිම කල් තබාගන්නා ද්‍රව්‍ය, වර්ණ හෝ ආකලන නොමැත—සෑම නිෂ්පාදනයකම පිරිසිදු සොබාදහම පමණි." }], collection: "අපගේ එකතුව", featured: "විශේෂ නිෂ්පාදන", viewAll: "සියල්ල බලන්න", none: "මේ මොහොතේ නිෂ්පාදන නොමැත.", checkBack: "කරුණාකර නැවත පරීක්ෂා කරන්න.", findStore: "වෙළඳසැල සොයන්න", findProducts: "ඔබ අසල රාජපුර නිෂ්පාදන සොයන්න", available: "ශ්‍රී ලංකාවේ පළාත් 9 පුරා ඖෂධහල්, ආයුර්වේද වෙළඳසැල් සහ සෞඛ්‍ය මධ්‍යස්ථානවලින් ලබා ගත හැක.", locator: "වෙළඳසැල් සෙවුම භාවිත කරන්න", badges: { Bestseller: "වැඩිම අලෙවි", Premium: "උසස්", New: "නව", Organic: "කාබනික" } },
  ta: { imageAlt: "மூலிகை மருந்து", pure: "100% தூய்மை", noAdditives: "சேர்க்கைகள் அல்லது பாதுகாப்புப் பொருட்கள் இல்லை", trusted: "1973 முதல் நம்பிக்கை", stats: ["பாரம்பரிய ஆண்டுகள்", "மூலிகை பொருட்கள்", "சேவை மாகாணங்கள்", "இயற்கை மற்றும் தூய்மை"], collectionAlt: "மூலிகை தயாரிப்புகள்", trust: "ஒரு நூற்றாண்டு நம்பிக்கை", heritage: "எங்கள் பாரம்பரியம்", legacy: "ஆயுர்வேத சிறப்பின் மரபு", heritageOne: "ராஜபுர ஹெர்பல் டிரக்ஸ் நிறுவனம் இலங்கையின் உயர்தர மூலிகை மருத்துவப் பொருட்களின் முன்னணி உற்பத்தியாளர் மற்றும் விநியோகஸ்தராக, இலங்கை சட்டத்தின் கீழ் பதிவு செய்யப்பட்டுள்ளது.", heritageTwo: "இன்று பண்டைய ஞானத்தை நவீன தரநிலைகளுடன் இணைத்து இயற்கையின் குணப்படுத்தும் பரிசுகளை இலங்கை முழுவதும் வீடுகளுக்குக் கொண்டு செல்கிறோம்—எப்போதும் தூய்மையாகவும் உண்மையாகவும்.", story: "எங்கள் கதையை அறியுங்கள்", why: "ஏன் எங்களைத் தேர்வு செய்ய வேண்டும்", difference: "ராஜபுர வித்தியாசம்", values: [{ title: "நிலையான ஆதாரம்", desc: "ஒவ்வொரு மூலிகையும் சான்றளிக்கப்பட்ட இயற்கை பண்ணைகள் மற்றும் தூய இலங்கை வனப்பகுதிகளிலிருந்து பொறுப்புடன் பெறப்படுகிறது." }, { title: "ஆயுர்வேத சான்றிதழ்", desc: "அனைத்து சூத்திரங்களும் இலங்கை ஆயுர்வேத துறை மற்றும் பாரம்பரிய மருத்துவர்களால் அங்கீகரிக்கப்பட்டவை." }, { title: "முழுமையான நலன்", desc: "எங்கள் தயாரிப்புகள் திரிதோஷக் கொள்கைகளின்படி உடல், மனம் மற்றும் ஆன்மாவை வளர்க்கின்றன." }, { title: "இரசாயனங்கள் இல்லை", desc: "செயற்கை பாதுகாப்புப் பொருட்கள், நிறங்கள் அல்லது சேர்க்கைகள் இல்லை—ஒவ்வொரு தயாரிப்பிலும் தூய இயற்கை மட்டுமே." }], collection: "எங்கள் தொகுப்பு", featured: "சிறப்பு தயாரிப்புகள்", viewAll: "அனைத்தையும் காண்க", none: "தற்போது தயாரிப்புகள் இல்லை.", checkBack: "தயவுசெய்து மீண்டும் பார்க்கவும்.", findStore: "கடையைக் கண்டறியவும்", findProducts: "உங்களுக்கு அருகில் ராஜபுர தயாரிப்புகளைக் கண்டறியவும்", available: "இலங்கையின் 9 மாகாணங்களிலும் மருந்தகங்கள், ஆயுர்வேத கடைகள் மற்றும் சுகாதார மையங்களில் கிடைக்கின்றன.", locator: "கடை கண்டுபிடிப்பைப் பயன்படுத்தவும்", badges: { Bestseller: "அதிக விற்பனை", Premium: "உயர்தரம்", New: "புதியது", Organic: "இயற்கை" } },
} as const;
